app:
    resource: "@AppBundle/Controller/"
    type:     annotation

sfdoctrine:
    resource: "@SfDoctrineBundle/Controller/"
    type:     annotation

homepage:
    path: "/homepage"
    defaults:
        _controller: AppBundle:Main:homepage
